# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: blackbox.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'blackbox.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x62lackbox.proto\x12\x08\x63rashlog\x1a\x0c\x63ommon.proto\"J\n\x0cStickCommand\x12\x0c\n\x04roll\x18\x01 \x01(\x01\x12\r\n\x05pitch\x18\x02 \x01(\x01\x12\x0b\n\x03yaw\x18\x03 \x01(\x01\x12\x10\n\x08throttle\x18\x04 \x01(\x01\"<\n\x07\x42\x61ttery\x12\x11\n\tvoltage_v\x18\x01 \x01(\x01\x12\x11\n\tcurrent_a\x18\x02 \x01(\x01\x12\x0b\n\x03mah\x18\x03 \x01(\x01\"\xea\x04\n\rBlackboxFrame\x12\x0f\n\x07time_us\x18\x01 \x01(\x04\x12\x0c\n\x04loop\x18\x02 \x01(\x04\x12#\n\x08gyro_dps\x18\x03 \x01(\x0b\x32\x11.crashlog.Vector3\x12#\n\x08gyro_raw\x18\x04 \x01(\x0b\x32\x11.crashlog.Vector3\x12 \n\x05\x61\x63\x63_g\x18\x05 \x01(\x0b\x32\x11.crashlog.Vector3\x12(\n\x08setpoint\x18\x06 \x01(\x0b\x32\x16.crashlog.StickCommand\x12*\n\nrc_command\x18\x07 \x01(\x0b\x32\x16.crashlog.StickCommand\x12\r\n\x05motor\x18\x08 \x03(\x01\x12\x0c\n\x04\x65rpm\x18\t \x03(\x01\x12\r\n\x05pid_p\x18\n \x03(\x01\x12\r\n\x05pid_i\x18\x0b \x03(\x01\x12\r\n\x05pid_d\x18\x0c \x03(\x01\x12\r\n\x05pid_f\x18\r \x03(\x01\x12\r\n\x05\x64\x65\x62ug\x18\x0e \x03(\x01\x12\"\n\x07\x62\x61ttery\x18\x0f \x01(\x0b\x32\x11.crashlog.Battery\x12\x10\n\x08\x62\x61ro_alt\x18\x10 \x01(\x01\x12\x0c\n\x04rssi\x18\x11 \x01(\x01\x12\x13\n\x0b\x66light_mode\x18\x12 \x01(\t\x12\x13\n\x0bstate_flags\x18\x13 \x01(\t\x12\x10\n\x08\x66\x61ilsafe\x18\x14 \x01(\t\x12\x11\n\trx_signal\x18\x15 \x01(\r\x12\x19\n\x11rx_channels_valid\x18\x16 \x01(\r\x12\x33\n\x06\x65xtras\x18\x17 \x03(\x0b\x32#.crashlog.BlackboxFrame.ExtrasEntry\x1a-\n\x0b\x45xtrasEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'blackbox_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BLACKBOXFRAME_EXTRASENTRY']._loaded_options = None
  _globals['_BLACKBOXFRAME_EXTRASENTRY']._serialized_options = b'8\001'
  _globals['_STICKCOMMAND']._serialized_start=42
  _globals['_STICKCOMMAND']._serialized_end=116
  _globals['_BATTERY']._serialized_start=118
  _globals['_BATTERY']._serialized_end=178
  _globals['_BLACKBOXFRAME']._serialized_start=181
  _globals['_BLACKBOXFRAME']._serialized_end=799
  _globals['_BLACKBOXFRAME_EXTRASENTRY']._serialized_start=754
  _globals['_BLACKBOXFRAME_EXTRASENTRY']._serialized_end=799
# @@protoc_insertion_point(module_scope)
