# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: imu.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'imu.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\timu.proto\x12\x08\x63rashlog\x1a\x0c\x63ommon.proto\",\n\tAxisFlags\x12\t\n\x01x\x18\x01 \x01(\x08\x12\t\n\x01y\x18\x02 \x01(\x08\x12\t\n\x01z\x18\x03 \x01(\x08\"\xd6\x01\n\tImuSample\x12\x14\n\x0chost_time_ns\x18\x01 \x01(\x04\x12\x12\n\nsensortime\x18\x02 \x01(\r\x12\"\n\x07\x61\x63\x63\x65l_g\x18\x03 \x01(\x0b\x32\x11.crashlog.Vector3\x12#\n\x08gyro_dps\x18\x04 \x01(\x0b\x32\x11.crashlog.Vector3\x12*\n\racc_saturated\x18\x05 \x01(\x0b\x32\x13.crashlog.AxisFlags\x12*\n\rgyr_saturated\x18\x06 \x01(\x0b\x32\x13.crashlog.AxisFlagsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'imu_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AXISFLAGS']._serialized_start=37
  _globals['_AXISFLAGS']._serialized_end=81
  _globals['_IMUSAMPLE']._serialized_start=84
  _globals['_IMUSAMPLE']._serialized_end=298
# @@protoc_insertion_point(module_scope)
